version: '3.7'
services:
  web:
    build: ./
    container_name: web
    command: python ./JBtest/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 12211221
      POSTGRES_USER: postgres
      POSTGRES_DB: JBdb
volumes:
  postgres_data:
