version: '3.7'
services:
  web:
    build: ./JBtest
    container_name: web
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${DATABASE}
volumes:
  postgres_data:
